/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package screens;

import classes.Database;
import classes.ProductPanel;
import java.awt.Font;
import java.awt.Image;
import java.awt.Toolkit;
import java.io.File;
import java.io.FileInputStream;
import java.sql.Blob;
import java.sql.SQLException;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.SwingConstants;
import javax.swing.SwingWorker;
import javax.swing.filechooser.FileNameExtensionFilter;
import utils.FontLoader;

/**
 *
 * @author ruki
 */
public class ItemDetails extends javax.swing.JFrame {
    static final int PICTURE_WIDTH = 96;
    static final int PICTURE_HEIGHT = 96;
    
    private ProductPanel productPanel;
    private Blob pictureBlob;
    Font inter;
    Font puritanBold;
    FontLoader fontLoader = new FontLoader();

    /**
     * Creates new form ItemDetails
     * @param productPanel
     */
    public ItemDetails(ProductPanel productPanel) {
        this.productPanel = productPanel;
        this.pictureBlob = this.productPanel.getPictureBlob();
        
        setFonts();
        initComponents();
        setFrameIcon();
        setShownImage();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        productNamePanel = new javax.swing.JTextField();
        clickableImagePanel = new javax.swing.JPanel();
        topPadding = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        imageLabel = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        hintLabel = new javax.swing.JLabel();
        bottomPadding = new javax.swing.JPanel();
        quantityPanel = new javax.swing.JTextField();
        saveButton = new javax.swing.JButton();
        deleteButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Edit product");
        setBackground(new java.awt.Color(255, 255, 255));
        setForeground(java.awt.Color.white);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createEmptyBorder(64, 64, 64, 64));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(puritanBold);
        jLabel1.setText(productPanel.getProductName()
        );

        productNamePanel.setBackground(new java.awt.Color(248, 248, 248));
        productNamePanel.setFont(inter);
        productNamePanel.setForeground(new java.awt.Color(40, 40, 40));
        productNamePanel.setText(productPanel.getProductName());
        productNamePanel.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(218, 218, 218)), javax.swing.BorderFactory.createEmptyBorder(0, 16, 0, 16)));

        clickableImagePanel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        clickableImagePanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                clickableImagePanelMouseClicked(evt);
            }
        });
        clickableImagePanel.setLayout(new javax.swing.BoxLayout(clickableImagePanel, javax.swing.BoxLayout.Y_AXIS));

        topPadding.setMaximumSize(new java.awt.Dimension(0, 8));
        topPadding.setMinimumSize(new java.awt.Dimension(0, 8));
        topPadding.setPreferredSize(new java.awt.Dimension(0, 8));
        topPadding.setRequestFocusEnabled(false);

        javax.swing.GroupLayout topPaddingLayout = new javax.swing.GroupLayout(topPadding);
        topPadding.setLayout(topPaddingLayout);
        topPaddingLayout.setHorizontalGroup(
            topPaddingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        topPaddingLayout.setVerticalGroup(
            topPaddingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        clickableImagePanel.add(topPadding);

        jPanel4.setOpaque(false);

        imageLabel.setFont(inter);
        imageLabel.setText("IMAGE");
        imageLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        imageLabel.setHorizontalAlignment(SwingConstants.CENTER);
        imageLabel.setMaximumSize(new java.awt.Dimension(96, 96));
        imageLabel.setMinimumSize(new java.awt.Dimension(96, 96));
        imageLabel.setName(""); // NOI18N
        imageLabel.setPreferredSize(new java.awt.Dimension(96, 96));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(imageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(imageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jPanel1.add(jPanel4);

        clickableImagePanel.add(jPanel1);

        hintLabel.setFont(inter);
        hintLabel.setText("UPLOAD IMAGE");
        hintLabel.setName(""); // NOI18N
        jPanel3.add(hintLabel);

        clickableImagePanel.add(jPanel3);

        bottomPadding.setMaximumSize(new java.awt.Dimension(0, 8));
        bottomPadding.setMinimumSize(new java.awt.Dimension(0, 8));
        bottomPadding.setRequestFocusEnabled(false);

        javax.swing.GroupLayout bottomPaddingLayout = new javax.swing.GroupLayout(bottomPadding);
        bottomPadding.setLayout(bottomPaddingLayout);
        bottomPaddingLayout.setHorizontalGroup(
            bottomPaddingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        bottomPaddingLayout.setVerticalGroup(
            bottomPaddingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        clickableImagePanel.add(bottomPadding);

        quantityPanel.setBackground(new java.awt.Color(248, 248, 248));
        quantityPanel.setFont(inter);
        quantityPanel.setForeground(new java.awt.Color(40, 40, 40));
        quantityPanel.setText(Integer.toString(productPanel.getQuantity())
        );
        quantityPanel.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(218, 218, 218)), javax.swing.BorderFactory.createEmptyBorder(0, 16, 0, 16)));
        quantityPanel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quantityPanelActionPerformed(evt);
            }
        });

        saveButton.setBackground(new java.awt.Color(40, 40, 40));
        saveButton.setFont(inter);
        saveButton.setForeground(new java.awt.Color(255, 255, 255));
        saveButton.setText("Save");
        saveButton.setBorderPainted(false);
        saveButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });

        deleteButton.setBackground(new java.awt.Color(197, 59, 59));
        deleteButton.setFont(inter);
        deleteButton.setForeground(new java.awt.Color(255, 255, 255));
        deleteButton.setText("Delete");
        deleteButton.setBorderPainted(false);
        deleteButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });

        cancelButton.setBackground(new java.awt.Color(245, 245, 245));
        cancelButton.setFont(inter);
        cancelButton.setForeground(new java.awt.Color(129, 129, 129));
        cancelButton.setText("Cancel");
        cancelButton.setBorderPainted(false);
        cancelButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(clickableImagePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(productNamePanel, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(quantityPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(saveButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(deleteButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 666, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(productNamePanel, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(quantityPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(clickableImagePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(saveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(deleteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void setFonts() {
        inter = fontLoader.interRegular(12);
        puritanBold = fontLoader.puritanBold(48);
    }
    
    private void setFrameIcon() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("../assets/logo.png")));
    }
    
    private void setShownImage() {
        if (pictureBlob == null) {
            /// Since there is no image, we just let it be.
            
            imageLabel.setText("");
            imageLabel.setIcon(new ImageIcon(getClass().getResource("/assets/Camera.png")));
            hintLabel.setText("Upload image");
            
            return;
        }
        
        System.out.println("There is a blob!");
        
        try {
            byte[] bytes = pictureBlob.getBytes(1l, (int)pictureBlob.length());
            var imageIcon = new ImageIcon(bytes);
            var scaled = scaleImageIcon(imageIcon, 96, 96);
            
            imageLabel.setText("");
            imageLabel.setIcon(scaled);
            hintLabel.setText("Change image");
        } catch (SQLException exception) {
            System.out.println("SQL Failed! Error: " + exception.getMessage());
        }
    }
    
    
    private static ImageIcon scaleImageIcon(ImageIcon originalIcon, int width, int height) {
        Image originalImage = originalIcon.getImage();

        // Create a scaled image
        Image scaledImage = originalImage.getScaledInstance(width, height, Image.SCALE_SMOOTH);

        // Create a new ImageIcon from the scaled image
        return new ImageIcon(scaledImage);
    }
    
    private void quantityPanelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quantityPanelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_quantityPanelActionPerformed

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        // TODO add your handling code here:
        
        /// Get the fields.
        var productName = productNamePanel.getText();
        var quantity = Integer.parseInt(quantityPanel.getText());
        var pictureBlob = this.pictureBlob;
        
        /// Update the database.
        var id = productPanel.getDatabaseId();
        
        var string = "UPDATE laes.products "
                   + "SET name = ?, quantity = ?, picture = ? "
                   + "WHERE id = ?";
        try (var stmt = Database.sqlConnection.prepareStatement(string)) {
            stmt.setString(1, productName);
            stmt.setInt(2, quantity);
            stmt.setBlob(3, pictureBlob);
            stmt.setInt(4, id);
            stmt.executeUpdate();
            
            System.out.println("Updated product with productId " + id);
        } catch (SQLException exception) { 
            System.out.println("SQL Failed! Error: " + exception.getMessage());
        }
        
        /// Update the UI.
        productPanel.setProductName(productName);
        productPanel.setQuantity(quantity);
        productPanel.setPictureBlob(pictureBlob);
        
        this.dispose();
    }//GEN-LAST:event_saveButtonActionPerformed

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
        // TODO add your handling code here:
        
        var id = productPanel.getDatabaseId();
        
        // remove this from the database.
        var string = "DELETE FROM laes.products WHERE id = ?";
        try (var stmt = Database.sqlConnection.prepareStatement(string)) {
            stmt.setInt(1, id);
            var affectedRows = stmt.executeUpdate();
            
            if (affectedRows > 0) {
                System.out.println("Succesfully removed product with id " + id);
            }
        } catch (SQLException exception) { 
            System.out.println("SQL Failed! Error: " + exception.getMessage());
        }
        
        // remove this from the ui.
        productPanel.getMain().removeProduct(id);
        this.dispose();
    }//GEN-LAST:event_deleteButtonActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        // TODO add your handling code here:  
        this.dispose();
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void clickableImagePanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clickableImagePanelMouseClicked
        // TODO add your handling code here:
        var chooser = new JFileChooser();
        var filter = new FileNameExtensionFilter(
            "JPG, GIF & PNG Images", 
            "jpg", 
            "jpeg", 
            "gif",
            "png"
        );
        
        chooser.setFileFilter(filter);
        chooser.showOpenDialog(null);
        var f = chooser.getSelectedFile();
        if (f == null) {
            return;
        }
        
        var filename = f.getAbsolutePath();
        
        System.out.println("The filename is " + filename);
        SwingWorker sw = new SwingWorker() {
            private Blob blob;
            private byte[] bytes;
            
            @Override
            protected Object doInBackground() throws Exception {
//                Thread.sleep(5000);//simulate large image takes long to load
                var file = new File(f.getAbsolutePath());
                try (var fis = new FileInputStream(file)) {
                    var buffer = new byte[(int)file.length()];
                    fis.read(buffer);
                    
                    bytes = buffer;
                }
                        
                
                blob = Database.sqlConnection.createBlob();
                blob.setBytes(1, bytes);
//                ii = new ImageIcon(scaleImage(120, 120, ImageIO.read(new File(f.getAbsolutePath()))));
                return null;
            }

            @Override
            protected void done() { 
                super.done();
                System.out.println("The bytes are: " + bytes.length);
                
                pictureBlob = blob;
                setShownImage();
                
            }
        };
        sw.execute();
    }//GEN-LAST:event_clickableImagePanelMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bottomPadding;
    private javax.swing.JButton cancelButton;
    private javax.swing.JPanel clickableImagePanel;
    private javax.swing.JButton deleteButton;
    private javax.swing.JLabel hintLabel;
    private javax.swing.JLabel imageLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTextField productNamePanel;
    private javax.swing.JTextField quantityPanel;
    private javax.swing.JButton saveButton;
    private javax.swing.JPanel topPadding;
    // End of variables declaration//GEN-END:variables
}
