/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package screens;

import java.awt.Font;
import java.awt.Color;
import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.ImageIcon;
import utils.FontLoader;
import classes.Database;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.util.Vector;
import javax.swing.RowFilter;
import javax.swing.event.DocumentListener;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;
import javax.swing.event.DocumentEvent;

/**
 *
 * @author rwill
 */
public class Main extends javax.swing.JFrame {
    FontLoader fontLoader = new FontLoader();
    Font inter;
    Font puritanBold;
    Font puritanBoldSmall;

    /**
     * Creates new form Reservations
     */
    public Main() {
        setFonts();
        initComponents();
        setFrameIcon();
        setFirstPanel();
        fetchReservations();
        fetchCustomers();
        setupReservationsSearch();
        setupCustomersSearch();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabsBtnGroup = new javax.swing.ButtonGroup();
        sidePnl = new javax.swing.JPanel();
        reservationsBtn = new javax.swing.JButton();
        customersBtn = new javax.swing.JButton();
        inventoryBtn = new javax.swing.JButton();
        aboutBtn = new javax.swing.JButton();
        logoutBtn = new javax.swing.JButton();
        logoLabel = new javax.swing.JLabel();
        mainPnl = new javax.swing.JPanel();
        reservationsPnl = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        searchReservations = new javax.swing.JTextField();
        addReservationBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        reservationsTbl = new javax.swing.JTable();
        reservationsTbl.getTableHeader().setFont(inter);
        customersPnl = new javax.swing.JPanel();
        aboutTitleLabel1 = new javax.swing.JLabel();
        searchCustomers = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        customersTbl = new javax.swing.JTable();
        reservationsTbl.getTableHeader().setFont(inter);
        aboutPnl = new javax.swing.JPanel();
        aboutTitle = new javax.swing.JPanel();
        aboutDesc = new javax.swing.JPanel();
        aboutHead1 = new javax.swing.JLabel();
        aboutDescText = new javax.swing.JLabel();
        aboutPrevimg1 = new javax.swing.JLabel();
        aboutPrevimg2 = new javax.swing.JLabel();
        aboutTitleLabel = new javax.swing.JLabel();
        inventoryPnl = new javax.swing.JPanel();
        title = new javax.swing.JLabel();
        searchInventory = new javax.swing.JTextField();
        addItemBtn = new javax.swing.JButton();
        box1 = new java.awt.Panel();
        minus = new javax.swing.JButton();
        plus = new javax.swing.JButton();
        label1 = new java.awt.Label();
        label3 = new java.awt.Label();
        jLabel4 = new javax.swing.JLabel();
        label10 = new java.awt.Label();
        box2 = new java.awt.Panel();
        label4 = new java.awt.Label();
        minus3 = new javax.swing.JButton();
        plus2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        label16 = new java.awt.Label();
        box3 = new java.awt.Panel();
        label6 = new java.awt.Label();
        minus5 = new javax.swing.JButton();
        plus4 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        label15 = new java.awt.Label();
        box4 = new java.awt.Panel();
        label8 = new java.awt.Label();
        minus7 = new javax.swing.JButton();
        plus7 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        label17 = new java.awt.Label();
        jSeparator1 = new javax.swing.JSeparator();
        box5 = new java.awt.Panel();
        label2 = new java.awt.Label();
        minus1 = new javax.swing.JButton();
        plus1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        label11 = new java.awt.Label();
        box6 = new java.awt.Panel();
        label5 = new java.awt.Label();
        jLabel6 = new javax.swing.JLabel();
        minus2 = new javax.swing.JButton();
        plus3 = new javax.swing.JButton();
        label12 = new java.awt.Label();
        box7 = new java.awt.Panel();
        label7 = new java.awt.Label();
        minus4 = new javax.swing.JButton();
        plus6 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        label13 = new java.awt.Label();
        box8 = new java.awt.Panel();
        label9 = new java.awt.Label();
        minus6 = new javax.swing.JButton();
        plus5 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        label14 = new java.awt.Label();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Lath's Auto-Electrical Shop");

        sidePnl.setBackground(new java.awt.Color(255, 255, 255));
        sidePnl.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.MatteBorder(0, 0, 0, 1, new java.awt.Color(218, 218, 218))
            , javax.swing.BorderFactory.createEmptyBorder(32, 32, 32, 32)));

    reservationsBtn.setBackground(new java.awt.Color(248, 248, 248));
    reservationsBtn.setFont(inter);
    reservationsBtn.setForeground(new java.awt.Color(35, 35, 35));
    reservationsBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/ClipboardCheckOutline.png"))); // NOI18N
    reservationsBtn.setText("  Reservations");
    reservationsBtn.setBorder(javax.swing.BorderFactory.createEmptyBorder(16, 16, 16, 16));
    reservationsBtn.setBorderPainted(false);
    reservationsBtn.setFocusPainted(false);
    reservationsBtn.setFocusable(false);
    reservationsBtn.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
    reservationsBtn.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            reservationsBtnActionPerformed(evt);
        }
    });

    customersBtn.setBackground(new java.awt.Color(255, 255, 255));
    customersBtn.setFont(inter);
    customersBtn.setForeground(new java.awt.Color(35, 35, 35));
    customersBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/UserOutline.png"))); // NOI18N
    customersBtn.setText("  Customers");
    customersBtn.setBorder(javax.swing.BorderFactory.createEmptyBorder(16, 16, 16, 16));
    customersBtn.setBorderPainted(false);
    customersBtn.setFocusPainted(false);
    customersBtn.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
    customersBtn.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            customersBtnActionPerformed(evt);
        }
    });

    inventoryBtn.setBackground(new java.awt.Color(255, 255, 255));
    inventoryBtn.setFont(inter);
    inventoryBtn.setForeground(new java.awt.Color(35, 35, 35));
    inventoryBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/ArchiveOutline.png"))); // NOI18N
    inventoryBtn.setText("  Inventory");
    inventoryBtn.setBorder(javax.swing.BorderFactory.createEmptyBorder(16, 16, 16, 16));
    inventoryBtn.setBorderPainted(false);
    inventoryBtn.setFocusPainted(false);
    inventoryBtn.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
    inventoryBtn.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            inventoryBtnActionPerformed(evt);
        }
    });

    aboutBtn.setBackground(new java.awt.Color(255, 255, 255));
    aboutBtn.setFont(inter);
    aboutBtn.setForeground(new java.awt.Color(35, 35, 35));
    aboutBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/ExclamationCircleOutline.png"))); // NOI18N
    aboutBtn.setText("  About");
    aboutBtn.setBorder(javax.swing.BorderFactory.createEmptyBorder(16, 16, 16, 16));
    aboutBtn.setBorderPainted(false);
    aboutBtn.setFocusPainted(false);
    aboutBtn.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
    aboutBtn.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            aboutBtnActionPerformed(evt);
        }
    });

    logoutBtn.setBackground(new java.awt.Color(40, 40, 40));
    logoutBtn.setFont(inter);
    logoutBtn.setForeground(new java.awt.Color(248, 248, 248));
    logoutBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/LogoutOutline.png"))); // NOI18N
    logoutBtn.setText("  Log out");
    logoutBtn.setBorder(javax.swing.BorderFactory.createEmptyBorder(16, 16, 16, 16));
    logoutBtn.setBorderPainted(false);
    logoutBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    logoutBtn.setFocusPainted(false);
    logoutBtn.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            logoutBtnActionPerformed(evt);
        }
    });

    logoLabel.setIcon(new ImageIcon(new javax.swing.ImageIcon(getClass().getResource("../assets/logo.png")).getImage().getScaledInstance(167, 128, Image.SCALE_SMOOTH)));
    logoLabel.setMaximumSize(new java.awt.Dimension(167, 128));
    logoLabel.setMinimumSize(new java.awt.Dimension(167, 128));

    javax.swing.GroupLayout sidePnlLayout = new javax.swing.GroupLayout(sidePnl);
    sidePnl.setLayout(sidePnlLayout);
    sidePnlLayout.setHorizontalGroup(
        sidePnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(sidePnlLayout.createSequentialGroup()
            .addGroup(sidePnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                .addComponent(logoLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(reservationsBtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 222, Short.MAX_VALUE)
                .addComponent(customersBtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(inventoryBtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(aboutBtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(logoutBtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );
    sidePnlLayout.setVerticalGroup(
        sidePnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(sidePnlLayout.createSequentialGroup()
            .addComponent(logoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(18, 18, 18)
            .addComponent(reservationsBtn)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(customersBtn)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(inventoryBtn)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(aboutBtn)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 228, Short.MAX_VALUE)
            .addComponent(logoutBtn))
    );

    getContentPane().add(sidePnl, java.awt.BorderLayout.WEST);

    mainPnl.setLayout(new java.awt.CardLayout());

    reservationsPnl.setBackground(new java.awt.Color(255, 255, 255));
    reservationsPnl.setBorder(javax.swing.BorderFactory.createEmptyBorder(32, 64, 32, 64));

    jLabel2.setFont(puritanBold);
    jLabel2.setForeground(new java.awt.Color(35, 35, 35));
    jLabel2.setText("RESERVATIONS");

    searchReservations.setBackground(new java.awt.Color(248, 248, 248));
    searchReservations.setFont(inter);
    searchReservations.setForeground(new java.awt.Color(129, 129, 129));
    searchReservations.setText("Search reservations");
    searchReservations.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(218, 218, 218)), javax.swing.BorderFactory.createEmptyBorder(16, 16, 16, 16)));
    searchReservations.addFocusListener(new java.awt.event.FocusAdapter() {
        public void focusGained(java.awt.event.FocusEvent evt) {
            searchReservationsFocusGained(evt);
        }
        public void focusLost(java.awt.event.FocusEvent evt) {
            searchReservationsFocusLost(evt);
        }
    });

    addReservationBtn.setBackground(new java.awt.Color(40, 40, 40));
    addReservationBtn.setFont(inter);
    addReservationBtn.setForeground(new java.awt.Color(248, 248, 248));
    addReservationBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/Plus.png"))); // NOI18N
    addReservationBtn.setText("  Add new reservation");
    addReservationBtn.setBorder(javax.swing.BorderFactory.createEmptyBorder(16, 16, 16, 16));
    addReservationBtn.setBorderPainted(false);
    addReservationBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    addReservationBtn.setFocusPainted(false);
    addReservationBtn.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            addReservationBtnActionPerformed(evt);
        }
    });

    reservationsTbl.setFont(inter);
    reservationsTbl.setModel(new javax.swing.table.DefaultTableModel(
        new Object [][] {
            {null, "Richard William Flores", "10/22/2023", "09764753058", "Alternator repair"},
            {null, null, null, null, null},
            {null, null, null, null, null},
            {null, null, null, null, null}
        },
        new String [] {
            "Reservation ID", "Name", "Date", "Contact number", "Service"
        }
    ) {
        Class[] types = new Class [] {
            java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
        };
        boolean[] canEdit = new boolean [] {
            false, false, false, false, false
        };

        public Class getColumnClass(int columnIndex) {
            return types [columnIndex];
        }

        public boolean isCellEditable(int rowIndex, int columnIndex) {
            return canEdit [columnIndex];
        }
    });
    reservationsTbl.setOpaque(false);
    reservationsTbl.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mouseClicked(java.awt.event.MouseEvent evt) {
            reservationsTblMouseClicked(evt);
        }
    });
    jScrollPane1.setViewportView(reservationsTbl);

    javax.swing.GroupLayout reservationsPnlLayout = new javax.swing.GroupLayout(reservationsPnl);
    reservationsPnl.setLayout(reservationsPnlLayout);
    reservationsPnlLayout.setHorizontalGroup(
        reservationsPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(reservationsPnlLayout.createSequentialGroup()
            .addContainerGap()
            .addGroup(reservationsPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 984, Short.MAX_VALUE)
                .addGroup(reservationsPnlLayout.createSequentialGroup()
                    .addComponent(jLabel2)
                    .addGap(0, 0, Short.MAX_VALUE))
                .addGroup(reservationsPnlLayout.createSequentialGroup()
                    .addComponent(searchReservations)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(addReservationBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addContainerGap())
    );
    reservationsPnlLayout.setVerticalGroup(
        reservationsPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(reservationsPnlLayout.createSequentialGroup()
            .addContainerGap()
            .addComponent(jLabel2)
            .addGap(18, 18, 18)
            .addGroup(reservationsPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(searchReservations, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(addReservationBtn))
            .addGap(18, 18, 18)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    mainPnl.add(reservationsPnl, "card3");

    customersPnl.setBackground(new java.awt.Color(255, 255, 255));
    customersPnl.setBorder(javax.swing.BorderFactory.createEmptyBorder(32, 64, 32, 64));

    aboutTitleLabel1.setFont(puritanBold);
    aboutTitleLabel1.setText("CUSTOMERS");

    searchCustomers.setBackground(new java.awt.Color(248, 248, 248));
    searchCustomers.setFont(inter);
    searchCustomers.setForeground(new java.awt.Color(129, 129, 129));
    searchCustomers.setText("Search customers");
    searchCustomers.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(218, 218, 218)), javax.swing.BorderFactory.createEmptyBorder(16, 16, 16, 16)));
    searchCustomers.addFocusListener(new java.awt.event.FocusAdapter() {
        public void focusGained(java.awt.event.FocusEvent evt) {
            searchCustomersFocusGained(evt);
        }
        public void focusLost(java.awt.event.FocusEvent evt) {
            searchCustomersFocusLost(evt);
        }
    });
    searchCustomers.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            searchCustomersActionPerformed(evt);
        }
    });

    customersTbl.setFont(inter);
    customersTbl.setModel(new javax.swing.table.DefaultTableModel(
        new Object [][] {
            {null, "Richard William Flores", "09764753058", "Alternator repair"},
            {null, null, null, null},
            {null, null, null, null},
            {null, null, null, null}
        },
        new String [] {
            "Customer ID", "Name", "Contact number", "Services"
        }
    ) {
        Class[] types = new Class [] {
            java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
        };
        boolean[] canEdit = new boolean [] {
            false, false, false, false
        };

        public Class getColumnClass(int columnIndex) {
            return types [columnIndex];
        }

        public boolean isCellEditable(int rowIndex, int columnIndex) {
            return canEdit [columnIndex];
        }
    });
    customersTbl.setOpaque(false);
    jScrollPane2.setViewportView(customersTbl);

    javax.swing.GroupLayout customersPnlLayout = new javax.swing.GroupLayout(customersPnl);
    customersPnl.setLayout(customersPnlLayout);
    customersPnlLayout.setHorizontalGroup(
        customersPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, customersPnlLayout.createSequentialGroup()
            .addContainerGap()
            .addGroup(customersPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                .addComponent(searchCustomers)
                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, customersPnlLayout.createSequentialGroup()
                    .addComponent(aboutTitleLabel1)
                    .addGap(0, 0, Short.MAX_VALUE))
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 984, Short.MAX_VALUE))
            .addContainerGap())
    );
    customersPnlLayout.setVerticalGroup(
        customersPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(customersPnlLayout.createSequentialGroup()
            .addContainerGap()
            .addComponent(aboutTitleLabel1)
            .addGap(18, 18, 18)
            .addComponent(searchCustomers, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(18, 18, 18)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap(34, Short.MAX_VALUE))
    );

    mainPnl.add(customersPnl, "card2");

    aboutPnl.setBackground(new java.awt.Color(255, 255, 255));
    aboutPnl.setBorder(javax.swing.BorderFactory.createEmptyBorder(32, 64, 32, 64));

    aboutTitle.setBackground(new java.awt.Color(255, 255, 255));

    javax.swing.GroupLayout aboutTitleLayout = new javax.swing.GroupLayout(aboutTitle);
    aboutTitle.setLayout(aboutTitleLayout);
    aboutTitleLayout.setHorizontalGroup(
        aboutTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGap(0, 0, Short.MAX_VALUE)
    );
    aboutTitleLayout.setVerticalGroup(
        aboutTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGap(0, 0, Short.MAX_VALUE)
    );

    aboutDesc.setBackground(new java.awt.Color(255, 255, 255));

    aboutHead1.setFont(puritanBoldSmall);
    aboutHead1.setText("<html>LATH’S AUTO-ELECTRICAL SHOP - YOUR TRUSTED <br>AUTO-ELECTRICAL SOLUTION!</html>");

    aboutDescText.setFont(new java.awt.Font("Inter", 0, 12)); // NOI18N
    aboutDescText.setForeground(new java.awt.Color(102, 102, 102));
    aboutDescText.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
    aboutDescText.setText("<html>At Lath’s Auto-Electrical Shop, we pride ourselves on being your one-stop destination for all things auto-electrical. With a passion for excellence and a commitment to customer satisfaction, we have been serving the automotive community in the Philippines since 2009.<html>");
    aboutDescText.setToolTipText("");
    aboutDescText.setVerticalAlignment(javax.swing.SwingConstants.TOP);
    aboutDescText.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

    aboutPrevimg1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/aboutprev1.png"))); // NOI18N

    aboutPrevimg2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/aboutprev2.png"))); // NOI18N

    javax.swing.GroupLayout aboutDescLayout = new javax.swing.GroupLayout(aboutDesc);
    aboutDesc.setLayout(aboutDescLayout);
    aboutDescLayout.setHorizontalGroup(
        aboutDescLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(aboutDescLayout.createSequentialGroup()
            .addGroup(aboutDescLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(aboutHead1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(aboutDescLayout.createSequentialGroup()
                    .addGroup(aboutDescLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(aboutDescLayout.createSequentialGroup()
                            .addComponent(aboutPrevimg1, javax.swing.GroupLayout.PREFERRED_SIZE, 385, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(27, 27, 27)
                            .addComponent(aboutPrevimg2, javax.swing.GroupLayout.PREFERRED_SIZE, 385, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(aboutDescText, javax.swing.GroupLayout.PREFERRED_SIZE, 858, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addContainerGap())
    );
    aboutDescLayout.setVerticalGroup(
        aboutDescLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(aboutDescLayout.createSequentialGroup()
            .addComponent(aboutHead1, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(aboutDescText, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(aboutDescLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                .addComponent(aboutPrevimg1, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(aboutPrevimg2, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addContainerGap(102, Short.MAX_VALUE))
    );

    aboutTitleLabel.setFont(puritanBold);
    aboutTitleLabel.setText("ABOUT");

    javax.swing.GroupLayout aboutPnlLayout = new javax.swing.GroupLayout(aboutPnl);
    aboutPnl.setLayout(aboutPnlLayout);
    aboutPnlLayout.setHorizontalGroup(
        aboutPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(aboutPnlLayout.createSequentialGroup()
            .addContainerGap()
            .addGroup(aboutPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(aboutPnlLayout.createSequentialGroup()
                    .addGap(22, 22, 22)
                    .addComponent(aboutTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(aboutPnlLayout.createSequentialGroup()
                    .addGroup(aboutPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(aboutTitleLabel)
                        .addComponent(aboutDesc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(0, 0, Short.MAX_VALUE))))
    );
    aboutPnlLayout.setVerticalGroup(
        aboutPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(aboutPnlLayout.createSequentialGroup()
            .addContainerGap()
            .addComponent(aboutTitleLabel)
            .addGap(18, 18, 18)
            .addComponent(aboutTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(aboutDesc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    mainPnl.add(aboutPnl, "card5");

    inventoryPnl.setBackground(new java.awt.Color(255, 255, 255));
    inventoryPnl.setBorder(javax.swing.BorderFactory.createEmptyBorder(32, 64, 32, 64));

    title.setFont(puritanBold);
    title.setForeground(new java.awt.Color(35, 35, 35));
    title.setText("INVENTORY");

    searchInventory.setBackground(new java.awt.Color(248, 248, 248));
    searchInventory.setFont(inter);
    searchInventory.setForeground(new java.awt.Color(129, 129, 129));
    searchInventory.setText("Search Inventory");
    searchInventory.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(218, 218, 218)), javax.swing.BorderFactory.createEmptyBorder(16, 16, 16, 16)));
    searchInventory.addFocusListener(new java.awt.event.FocusAdapter() {
        public void focusGained(java.awt.event.FocusEvent evt) {
            searchInventoryFocusGained(evt);
        }
        public void focusLost(java.awt.event.FocusEvent evt) {
            searchInventoryFocusLost(evt);
        }
    });

    addItemBtn.setBackground(new java.awt.Color(40, 40, 40));
    addItemBtn.setFont(inter);
    addItemBtn.setForeground(new java.awt.Color(248, 248, 248));
    addItemBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/Plus.png"))); // NOI18N
    addItemBtn.setText("Add New Item");
    addItemBtn.setBorder(javax.swing.BorderFactory.createEmptyBorder(16, 16, 16, 16));
    addItemBtn.setBorderPainted(false);
    addItemBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    addItemBtn.setFocusPainted(false);
    addItemBtn.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            addItemBtnActionPerformed(evt);
        }
    });

    box1.setBackground(new java.awt.Color(244, 244, 244));

    minus.setBackground(java.awt.Color.lightGray);
    minus.setText("-");
    minus.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            minusActionPerformed(evt);
        }
    });

    plus.setBackground(java.awt.Color.lightGray);
    plus.setForeground(new java.awt.Color(40, 40, 40));
    plus.setText("+");
    plus.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            plusActionPerformed(evt);
        }
    });

    label1.setText("label1");

    label3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
    label3.setText("Alternator");

    jLabel4.setText("jLabel1");

    label10.setForeground(java.awt.Color.gray);
    label10.setText("5 pcs");

    javax.swing.GroupLayout box1Layout = new javax.swing.GroupLayout(box1);
    box1.setLayout(box1Layout);
    box1Layout.setHorizontalGroup(
        box1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, box1Layout.createSequentialGroup()
            .addGap(16, 16, 16)
            .addComponent(minus, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
            .addGroup(box1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(box1Layout.createSequentialGroup()
                    .addGap(10, 10, 10)
                    .addComponent(label10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(box1Layout.createSequentialGroup()
                    .addComponent(label3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(23, 23, 23)
                    .addComponent(plus, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGap(14, 14, 14))
        .addGroup(box1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(box1Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(46, Short.MAX_VALUE)))
    );
    box1Layout.setVerticalGroup(
        box1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(box1Layout.createSequentialGroup()
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(box1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, box1Layout.createSequentialGroup()
                    .addGroup(box1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(minus)
                        .addComponent(plus))
                    .addGap(21, 21, 21))
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, box1Layout.createSequentialGroup()
                    .addComponent(label3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(6, 6, 6)
                    .addComponent(label10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
        .addGroup(box1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(box1Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(46, Short.MAX_VALUE)))
    );

    box2.setBackground(new java.awt.Color(244, 244, 244));

    label4.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
    label4.setText("Alternator");

    minus3.setBackground(java.awt.Color.lightGray);
    minus3.setText("-");
    minus3.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            minus3ActionPerformed(evt);
        }
    });

    plus2.setBackground(java.awt.Color.lightGray);
    plus2.setForeground(new java.awt.Color(40, 40, 40));
    plus2.setText("+");
    plus2.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            plus2ActionPerformed(evt);
        }
    });

    jLabel1.setText("jLabel1");

    label16.setForeground(java.awt.Color.gray);
    label16.setText("5 pcs");

    javax.swing.GroupLayout box2Layout = new javax.swing.GroupLayout(box2);
    box2.setLayout(box2Layout);
    box2Layout.setHorizontalGroup(
        box2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(box2Layout.createSequentialGroup()
            .addGap(45, 45, 45)
            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, box2Layout.createSequentialGroup()
            .addGap(14, 14, 14)
            .addComponent(minus3, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(label4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(24, 24, 24)
            .addComponent(plus2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(14, 14, 14))
        .addGroup(box2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, box2Layout.createSequentialGroup()
                .addContainerGap(84, Short.MAX_VALUE)
                .addComponent(label16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(82, 82, 82)))
    );
    box2Layout.setVerticalGroup(
        box2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, box2Layout.createSequentialGroup()
            .addGroup(box2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                .addGroup(box2Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(plus2))
                .addGroup(box2Layout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(box2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(box2Layout.createSequentialGroup()
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(minus3))
                        .addGroup(box2Layout.createSequentialGroup()
                            .addGap(1, 1, 1)
                            .addComponent(label4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
            .addGap(21, 21, 21))
        .addGroup(box2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, box2Layout.createSequentialGroup()
                .addContainerGap(170, Short.MAX_VALUE)
                .addComponent(label16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap()))
    );

    box3.setBackground(new java.awt.Color(244, 244, 244));

    label6.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
    label6.setText("Alternator");

    minus5.setBackground(java.awt.Color.lightGray);
    minus5.setText("-");
    minus5.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            minus5ActionPerformed(evt);
        }
    });

    plus4.setBackground(java.awt.Color.lightGray);
    plus4.setForeground(new java.awt.Color(40, 40, 40));
    plus4.setText("+");
    plus4.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            plus4ActionPerformed(evt);
        }
    });

    jLabel8.setText("jLabel1");

    label15.setForeground(java.awt.Color.gray);
    label15.setText("5 pcs");

    javax.swing.GroupLayout box3Layout = new javax.swing.GroupLayout(box3);
    box3.setLayout(box3Layout);
    box3Layout.setHorizontalGroup(
        box3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(box3Layout.createSequentialGroup()
            .addGap(15, 15, 15)
            .addComponent(minus5, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(box3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(box3Layout.createSequentialGroup()
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                    .addComponent(label6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(24, 24, 24))
                .addGroup(box3Layout.createSequentialGroup()
                    .addGap(42, 42, 42)
                    .addComponent(label15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
            .addComponent(plus4, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(14, 14, 14))
        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, box3Layout.createSequentialGroup()
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(44, 44, 44))
    );
    box3Layout.setVerticalGroup(
        box3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, box3Layout.createSequentialGroup()
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(box3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                .addGroup(box3Layout.createSequentialGroup()
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(box3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(minus5)
                        .addComponent(plus4))
                    .addGap(20, 20, 20))
                .addGroup(box3Layout.createSequentialGroup()
                    .addGap(2, 2, 2)
                    .addComponent(label6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(label15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap())))
    );

    box4.setBackground(new java.awt.Color(244, 244, 244));

    label8.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
    label8.setText("Alternator");

    minus7.setBackground(java.awt.Color.lightGray);
    minus7.setText("-");
    minus7.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            minus7ActionPerformed(evt);
        }
    });

    plus7.setBackground(java.awt.Color.lightGray);
    plus7.setForeground(new java.awt.Color(40, 40, 40));
    plus7.setText("+");
    plus7.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            plus7ActionPerformed(evt);
        }
    });

    jLabel9.setText("jLabel1");

    label17.setForeground(java.awt.Color.gray);
    label17.setText("5 pcs");

    javax.swing.GroupLayout box4Layout = new javax.swing.GroupLayout(box4);
    box4.setLayout(box4Layout);
    box4Layout.setHorizontalGroup(
        box4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, box4Layout.createSequentialGroup()
            .addGap(14, 14, 14)
            .addComponent(minus7, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
            .addComponent(label8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(24, 24, 24)
            .addComponent(plus7, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(14, 14, 14))
        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, box4Layout.createSequentialGroup()
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(44, 44, 44))
        .addGroup(box4Layout.createSequentialGroup()
            .addGap(78, 78, 78)
            .addComponent(label17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );
    box4Layout.setVerticalGroup(
        box4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, box4Layout.createSequentialGroup()
            .addContainerGap(10, Short.MAX_VALUE)
            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(18, 18, 18)
            .addGroup(box4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                .addComponent(label8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(box4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(minus7)
                    .addComponent(plus7)))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(label17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap())
    );

    box5.setBackground(new java.awt.Color(244, 244, 244));

    label2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
    label2.setText("Bearings");

    minus1.setBackground(java.awt.Color.lightGray);
    minus1.setText("-");
    minus1.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            minus1ActionPerformed(evt);
        }
    });

    plus1.setBackground(java.awt.Color.lightGray);
    plus1.setForeground(new java.awt.Color(40, 40, 40));
    plus1.setText("+");
    plus1.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            plus1ActionPerformed(evt);
        }
    });

    jLabel5.setText("jLabel1");

    label11.setForeground(java.awt.Color.gray);
    label11.setText("5 pcs");

    javax.swing.GroupLayout box5Layout = new javax.swing.GroupLayout(box5);
    box5.setLayout(box5Layout);
    box5Layout.setHorizontalGroup(
        box5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, box5Layout.createSequentialGroup()
            .addGap(15, 15, 15)
            .addComponent(minus1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(box5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(box5Layout.createSequentialGroup()
                    .addGap(10, 10, 10)
                    .addComponent(label11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGap(27, 27, 27)
            .addComponent(plus1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(14, 14, 14))
        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, box5Layout.createSequentialGroup()
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(43, 43, 43))
    );
    box5Layout.setVerticalGroup(
        box5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(box5Layout.createSequentialGroup()
            .addContainerGap(42, Short.MAX_VALUE)
            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(1, 1, 1)
            .addGroup(box5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, box5Layout.createSequentialGroup()
                    .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(3, 3, 3)
                    .addComponent(label11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap())
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, box5Layout.createSequentialGroup()
                    .addGroup(box5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(plus1)
                        .addComponent(minus1))
                    .addGap(25, 25, 25))))
    );

    box6.setBackground(new java.awt.Color(244, 244, 244));

    label5.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
    label5.setText("Alternator");

    jLabel6.setText("jLabel1");

    minus2.setBackground(java.awt.Color.lightGray);
    minus2.setText("-");
    minus2.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            minus2ActionPerformed(evt);
        }
    });

    plus3.setBackground(java.awt.Color.lightGray);
    plus3.setForeground(new java.awt.Color(40, 40, 40));
    plus3.setText("+");
    plus3.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            plus3ActionPerformed(evt);
        }
    });

    label12.setForeground(java.awt.Color.gray);
    label12.setText("5 pcs");

    javax.swing.GroupLayout box6Layout = new javax.swing.GroupLayout(box6);
    box6.setLayout(box6Layout);
    box6Layout.setHorizontalGroup(
        box6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, box6Layout.createSequentialGroup()
            .addGap(14, 14, 14)
            .addComponent(minus2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(box6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(box6Layout.createSequentialGroup()
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                    .addComponent(label5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(23, 23, 23))
                .addGroup(box6Layout.createSequentialGroup()
                    .addGap(45, 45, 45)
                    .addComponent(label12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
            .addComponent(plus3, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(16, 16, 16))
        .addGroup(box6Layout.createSequentialGroup()
            .addGap(44, 44, 44)
            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );
    box6Layout.setVerticalGroup(
        box6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(box6Layout.createSequentialGroup()
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(1, 1, 1)
            .addGroup(box6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, box6Layout.createSequentialGroup()
                    .addGroup(box6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(plus3)
                        .addComponent(minus2))
                    .addGap(24, 24, 24))
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, box6Layout.createSequentialGroup()
                    .addComponent(label5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(3, 3, 3)
                    .addComponent(label12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap())))
    );

    box7.setBackground(new java.awt.Color(244, 244, 244));

    label7.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
    label7.setText("Alternator");

    minus4.setBackground(java.awt.Color.lightGray);
    minus4.setText("-");
    minus4.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            minus4ActionPerformed(evt);
        }
    });

    plus6.setBackground(java.awt.Color.lightGray);
    plus6.setForeground(new java.awt.Color(40, 40, 40));
    plus6.setText("+");
    plus6.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            plus6ActionPerformed(evt);
        }
    });

    jLabel3.setText("jLabel1");

    label13.setForeground(java.awt.Color.gray);
    label13.setText("5 pcs");

    javax.swing.GroupLayout box7Layout = new javax.swing.GroupLayout(box7);
    box7.setLayout(box7Layout);
    box7Layout.setHorizontalGroup(
        box7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, box7Layout.createSequentialGroup()
            .addGap(14, 14, 14)
            .addComponent(minus4, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(box7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(label7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(box7Layout.createSequentialGroup()
                    .addGap(10, 10, 10)
                    .addComponent(label13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGap(24, 24, 24)
            .addComponent(plus6, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(14, 14, 14))
        .addGroup(box7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, box7Layout.createSequentialGroup()
                .addContainerGap(52, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)))
    );
    box7Layout.setVerticalGroup(
        box7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(box7Layout.createSequentialGroup()
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(box7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, box7Layout.createSequentialGroup()
                    .addGroup(box7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(minus4)
                        .addComponent(plus6))
                    .addGap(22, 22, 22))
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, box7Layout.createSequentialGroup()
                    .addComponent(label7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(label13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap())))
        .addGroup(box7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(box7Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(60, Short.MAX_VALUE)))
    );

    box8.setBackground(new java.awt.Color(244, 244, 244));

    label9.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
    label9.setText("Alternator");

    minus6.setBackground(java.awt.Color.lightGray);
    minus6.setText("-");
    minus6.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            minus6ActionPerformed(evt);
        }
    });

    plus5.setBackground(java.awt.Color.lightGray);
    plus5.setForeground(new java.awt.Color(40, 40, 40));
    plus5.setText("+");
    plus5.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            plus5ActionPerformed(evt);
        }
    });

    jLabel10.setText("jLabel1");

    label14.setForeground(java.awt.Color.gray);
    label14.setText("5 pcs");

    javax.swing.GroupLayout box8Layout = new javax.swing.GroupLayout(box8);
    box8.setLayout(box8Layout);
    box8Layout.setHorizontalGroup(
        box8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, box8Layout.createSequentialGroup()
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(44, 44, 44))
        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, box8Layout.createSequentialGroup()
            .addGap(14, 14, 14)
            .addComponent(minus6, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
            .addGroup(box8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(box8Layout.createSequentialGroup()
                    .addGap(10, 10, 10)
                    .addComponent(label14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(box8Layout.createSequentialGroup()
                    .addComponent(label9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(23, 23, 23)
                    .addComponent(plus5, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGap(14, 14, 14))
    );
    box8Layout.setVerticalGroup(
        box8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, box8Layout.createSequentialGroup()
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(box8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(box8Layout.createSequentialGroup()
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(box8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(minus6)
                        .addComponent(plus5)))
                .addGroup(box8Layout.createSequentialGroup()
                    .addGap(1, 1, 1)
                    .addComponent(label9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGap(2, 2, 2)
            .addComponent(label14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
    );

    javax.swing.GroupLayout inventoryPnlLayout = new javax.swing.GroupLayout(inventoryPnl);
    inventoryPnl.setLayout(inventoryPnlLayout);
    inventoryPnlLayout.setHorizontalGroup(
        inventoryPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, inventoryPnlLayout.createSequentialGroup()
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(358, 358, 358))
        .addGroup(inventoryPnlLayout.createSequentialGroup()
            .addGap(56, 56, 56)
            .addGroup(inventoryPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(inventoryPnlLayout.createSequentialGroup()
                    .addComponent(title)
                    .addGap(0, 0, Short.MAX_VALUE))
                .addGroup(inventoryPnlLayout.createSequentialGroup()
                    .addComponent(searchInventory)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(addItemBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(inventoryPnlLayout.createSequentialGroup()
                    .addGroup(inventoryPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(box1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(box5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGap(60, 60, 60)
                    .addGroup(inventoryPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(box2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(box6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(inventoryPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(box3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(box7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGap(60, 60, 60)
                    .addGroup(inventoryPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(box4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(box8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
            .addContainerGap())
    );
    inventoryPnlLayout.setVerticalGroup(
        inventoryPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(inventoryPnlLayout.createSequentialGroup()
            .addComponent(title, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(24, 24, 24)
            .addGroup(inventoryPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(searchInventory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(addItemBtn))
            .addGap(35, 35, 35)
            .addGroup(inventoryPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                .addComponent(box4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(box2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(box1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(box3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(6, 6, 6)
            .addGroup(inventoryPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(box7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(box5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(box6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(box8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addContainerGap())
    );

    mainPnl.add(inventoryPnl, "card5");

    getContentPane().add(mainPnl, java.awt.BorderLayout.CENTER);

    pack();
    setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    
    public void fetchReservations() {
        try {
            String query = "SELECT * FROM laes.reservations ORDER BY date ASC";
            PreparedStatement pstmt = Database.sqlConnection.prepareStatement(query);
            
            ResultSet rs = pstmt.executeQuery();
            ResultSetMetaData rsMetaData = rs.getMetaData();
            
            int tableCount = rsMetaData.getColumnCount();
            
            DefaultTableModel recordTable = (DefaultTableModel) reservationsTbl.getModel();
            
            recordTable.setRowCount(0);
            
            while (rs.next()) {
                Vector columnData = new Vector();
                
                for (int i = 1; i < tableCount; i++) {
                    columnData.add(rs.getString("reservationId"));
                    columnData.add(rs.getString("name"));
                    columnData.add(rs.getString("date"));
                    columnData.add(rs.getString("contactNumber"));
                    columnData.add(rs.getString("typeOfService"));
                }
                
                recordTable.addRow(columnData);
            }
        } catch (SQLException e) {
            System.out.println(e);
        }
    }
    
    public void fetchCustomers() {
        try {
            String query = "SELECT * FROM laes.customers ORDER BY name ASC";
            PreparedStatement pstmt = Database.sqlConnection.prepareStatement(query);
            
            ResultSet rs = pstmt.executeQuery();
            ResultSetMetaData rsMetaData = rs.getMetaData();
            
            int tableCount = rsMetaData.getColumnCount();
            
            DefaultTableModel recordTable = (DefaultTableModel) customersTbl.getModel();
            
            recordTable.setRowCount(0);
            
            while (rs.next()) {
                Vector columnData = new Vector();
                
                for (int i = 1; i < tableCount; i++) {
                    columnData.add(rs.getString("customerId"));
                    columnData.add(rs.getString("name"));
                    columnData.add(rs.getString("contactNumber"));
                    columnData.add(rs.getString("services"));
                }
                
                recordTable.addRow(columnData);
            }
        } catch (SQLException e) {
            System.out.println(e);
        }
    }
    
    private void setFonts() {
        inter = fontLoader.interRegular(12);
        puritanBold = fontLoader.puritanBold(44);
        puritanBoldSmall = fontLoader.puritanBold(32);
    }

    private void setFrameIcon() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("../assets/logo.png")));
    }
    
    private void setupReservationsSearch() {
        TableRowSorter<TableModel> rowSorter = new TableRowSorter<>(reservationsTbl.getModel());
        
        reservationsTbl.setRowSorter(rowSorter);
        
        searchReservations.getDocument().addDocumentListener(new DocumentListener(){
            @Override
            public void insertUpdate(DocumentEvent e) {
                String text = searchReservations.getText();

                if (!text.equals("Search reservations")) {
                    if (text.trim().length() == 0) {
                        rowSorter.setRowFilter(null);
                    } else {
                        rowSorter.setRowFilter(RowFilter.regexFilter("(?i)" + text));
                    }
                }
            }

            @Override
            public void removeUpdate(DocumentEvent e) {
                String text = searchReservations.getText();

                if (!text.equals("Search reservations")) {
                    if (text.trim().length() == 0) {
                        rowSorter.setRowFilter(null);
                    } else {
                        rowSorter.setRowFilter(RowFilter.regexFilter("(?i)" + text));
                    }
                }
            }

            @Override
            public void changedUpdate(DocumentEvent e) {
                throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
            }

        });
    }
    
    private void setupCustomersSearch() {
        TableRowSorter<TableModel> rowSorter = new TableRowSorter<>(customersTbl.getModel());
        
        customersTbl.setRowSorter(rowSorter);
        
        searchCustomers.getDocument().addDocumentListener(new DocumentListener(){
            @Override
            public void insertUpdate(DocumentEvent e) {
                String text = searchCustomers.getText();

                if (!text.equals("Search customers")) {
                    if (text.trim().length() == 0) {
                        rowSorter.setRowFilter(null);
                    } else {
                        rowSorter.setRowFilter(RowFilter.regexFilter("(?i)" + text));
                    }
                }
            }

            @Override
            public void removeUpdate(DocumentEvent e) {
                String text = searchCustomers.getText();

                if (!text.equals("Search customers")) {
                    if (text.trim().length() == 0) {
                        rowSorter.setRowFilter(null);
                    } else {
                        rowSorter.setRowFilter(RowFilter.regexFilter("(?i)" + text));
                    }
                }
            }

            @Override
            public void changedUpdate(DocumentEvent e) {
                throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
            }

        });
    }

    private void setFirstPanel() {
        mainPnl.removeAll();
        mainPnl.add(reservationsPnl);
        mainPnl.repaint();
        mainPnl.revalidate();
    }

    private void customersBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customersBtnActionPerformed
        mainPnl.removeAll();
        mainPnl.add(customersPnl);
        mainPnl.repaint();
        mainPnl.revalidate();
    }//GEN-LAST:event_customersBtnActionPerformed

    private void inventoryBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inventoryBtnActionPerformed
        mainPnl.removeAll();
        mainPnl.add(inventoryPnl);
        mainPnl.repaint();
        mainPnl.revalidate();
    }//GEN-LAST:event_inventoryBtnActionPerformed

    private void aboutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aboutBtnActionPerformed
        mainPnl.removeAll();
        mainPnl.add(aboutPnl);
        mainPnl.repaint();
        mainPnl.revalidate();
    }//GEN-LAST:event_aboutBtnActionPerformed

    private void reservationsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reservationsBtnActionPerformed
        mainPnl.removeAll();
        mainPnl.add(reservationsPnl);
        mainPnl.repaint();
        mainPnl.revalidate();
    }//GEN-LAST:event_reservationsBtnActionPerformed

    private void logoutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutBtnActionPerformed
        this.setVisible(false);
        this.dispose();
        
        new LogIn().setVisible(true);
    }//GEN-LAST:event_logoutBtnActionPerformed

    private void addReservationBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addReservationBtnActionPerformed
        NewReservation newReservation = new NewReservation(this);

        newReservation.setVisible(true);
    }//GEN-LAST:event_addReservationBtnActionPerformed

    private void searchReservationsFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_searchReservationsFocusLost
        String searchValue = searchReservations.getText();

        if (searchValue.equals("")) {
            searchReservations.setText("Search reservations");
            searchReservations.setForeground(new Color(129, 129, 129));
        }
    }//GEN-LAST:event_searchReservationsFocusLost

    private void searchReservationsFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_searchReservationsFocusGained
        String searchValue = searchReservations.getText();

        if (searchValue.equals("Search reservations")) {
            searchReservations.setText("");
            searchReservations.setForeground(new Color(35, 35, 35));
        }
    }//GEN-LAST:event_searchReservationsFocusGained

    private void searchCustomersFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_searchCustomersFocusGained
        String searchValue = searchCustomers.getText();

        if (searchValue.equals("Search customers")) {
            searchCustomers.setText("");
            searchCustomers.setForeground(new Color(35, 35, 35));
        }
    }//GEN-LAST:event_searchCustomersFocusGained

    private void searchCustomersFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_searchCustomersFocusLost
        String searchValue = searchCustomers.getText();

        if (searchValue.equals("")) {
            searchCustomers.setText("Search customers");
            searchCustomers.setForeground(new Color(129, 129, 129));
        }
    }//GEN-LAST:event_searchCustomersFocusLost

    private void searchCustomersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchCustomersActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchCustomersActionPerformed

    private void searchInventoryFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_searchInventoryFocusGained
        String searchValue = searchInventory.getText();

        if (searchValue.equals("Search inventory")) {
            searchInventory.setText("");
            searchInventory.setForeground(new Color(35, 35, 35));
        }
    }//GEN-LAST:event_searchInventoryFocusGained

    private void searchInventoryFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_searchInventoryFocusLost
        String searchValue = searchInventory.getText();

        if (searchValue.equals("")) {
            searchInventory.setText("Search inventory");
            searchInventory.setForeground(new Color(129, 129, 129));
        }
    }//GEN-LAST:event_searchInventoryFocusLost

    private void addItemBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addItemBtnActionPerformed
        NewInventoryItem newInventoryItem = new NewInventoryItem();
        
        newInventoryItem.setVisible(true);
    }//GEN-LAST:event_addItemBtnActionPerformed

    private void minusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_minusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_minusActionPerformed

    private void plusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_plusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_plusActionPerformed

    private void minus3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_minus3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_minus3ActionPerformed

    private void plus2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_plus2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_plus2ActionPerformed

    private void minus5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_minus5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_minus5ActionPerformed

    private void plus4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_plus4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_plus4ActionPerformed

    private void minus7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_minus7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_minus7ActionPerformed

    private void plus7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_plus7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_plus7ActionPerformed

    private void minus1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_minus1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_minus1ActionPerformed

    private void plus1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_plus1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_plus1ActionPerformed

    private void minus2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_minus2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_minus2ActionPerformed

    private void plus3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_plus3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_plus3ActionPerformed

    private void minus4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_minus4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_minus4ActionPerformed

    private void plus6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_plus6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_plus6ActionPerformed

    private void minus6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_minus6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_minus6ActionPerformed

    private void plus5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_plus5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_plus5ActionPerformed

    private void reservationsTblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reservationsTblMouseClicked
        DefaultTableModel RecordTable = (DefaultTableModel) reservationsTbl.getModel();
        int selectedRows = reservationsTbl.getSelectedRow();
          
        String reservationId = RecordTable.getValueAt(selectedRows,0).toString();
        
        new ReservationDetails(this, reservationId).setVisible(true);
    }//GEN-LAST:event_reservationsTblMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            javax.swing.UIManager.setLookAndFeel("com.sun.java.swing.plaf.windows.WindowsLookAndFeel");
        } catch (Exception e) {
            System.out.println("UIManager Exception : " + e);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton aboutBtn;
    private javax.swing.JPanel aboutDesc;
    private javax.swing.JLabel aboutDescText;
    private javax.swing.JLabel aboutHead1;
    private javax.swing.JPanel aboutPnl;
    private javax.swing.JLabel aboutPrevimg1;
    private javax.swing.JLabel aboutPrevimg2;
    private javax.swing.JPanel aboutTitle;
    private javax.swing.JLabel aboutTitleLabel;
    private javax.swing.JLabel aboutTitleLabel1;
    private javax.swing.JButton addItemBtn;
    private javax.swing.JButton addReservationBtn;
    private java.awt.Panel box1;
    private java.awt.Panel box2;
    private java.awt.Panel box3;
    private java.awt.Panel box4;
    private java.awt.Panel box5;
    private java.awt.Panel box6;
    private java.awt.Panel box7;
    private java.awt.Panel box8;
    private javax.swing.JButton customersBtn;
    private javax.swing.JPanel customersPnl;
    private javax.swing.JTable customersTbl;
    private javax.swing.JButton inventoryBtn;
    private javax.swing.JPanel inventoryPnl;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private java.awt.Label label1;
    private java.awt.Label label10;
    private java.awt.Label label11;
    private java.awt.Label label12;
    private java.awt.Label label13;
    private java.awt.Label label14;
    private java.awt.Label label15;
    private java.awt.Label label16;
    private java.awt.Label label17;
    private java.awt.Label label2;
    private java.awt.Label label3;
    private java.awt.Label label4;
    private java.awt.Label label5;
    private java.awt.Label label6;
    private java.awt.Label label7;
    private java.awt.Label label8;
    private java.awt.Label label9;
    private javax.swing.JLabel logoLabel;
    private javax.swing.JButton logoutBtn;
    private javax.swing.JPanel mainPnl;
    private javax.swing.JButton minus;
    private javax.swing.JButton minus1;
    private javax.swing.JButton minus2;
    private javax.swing.JButton minus3;
    private javax.swing.JButton minus4;
    private javax.swing.JButton minus5;
    private javax.swing.JButton minus6;
    private javax.swing.JButton minus7;
    private javax.swing.JButton plus;
    private javax.swing.JButton plus1;
    private javax.swing.JButton plus2;
    private javax.swing.JButton plus3;
    private javax.swing.JButton plus4;
    private javax.swing.JButton plus5;
    private javax.swing.JButton plus6;
    private javax.swing.JButton plus7;
    private javax.swing.JButton reservationsBtn;
    private javax.swing.JPanel reservationsPnl;
    private javax.swing.JTable reservationsTbl;
    private javax.swing.JTextField searchCustomers;
    private javax.swing.JTextField searchInventory;
    private javax.swing.JTextField searchReservations;
    private javax.swing.JPanel sidePnl;
    private javax.swing.ButtonGroup tabsBtnGroup;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables
}
