/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package screens;

import com.github.lgooddatepicker.components.DatePicker;
import java.awt.Font;
import java.awt.Color;
import javax.swing.JComponent;
import javax.swing.border.EmptyBorder;
import javax.swing.AbstractButton;
import javax.swing.UIManager;
import utils.FontLoader;

/**
 *
 * @author rwill
 */
public class NewReservation extends javax.swing.JFrame {
    FontLoader fontLoader = new FontLoader();
    Font inter;
    Font puritanBold;

    /**
     * Creates new form NewReservation
     */
    public NewReservation() {
        setFonts();
        initComponents();
        focus();
    }
    
    private void setFonts() {
        inter = fontLoader.interRegular(12);
        puritanBold = fontLoader.puritanBold(44);
    }
    
    private void focus() {
        mainPnl.requestFocus();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPnl = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        contactTxt = new javax.swing.JTextField();
        nameTxt = new javax.swing.JTextField();
        typeOfReservation = new javax.swing.JComboBox<>();
        for (int i = 0; i < typeOfReservation.getComponentCount(); i++) 
        {
            if (typeOfReservation.getComponent(i) instanceof JComponent) {
                ((JComponent) typeOfReservation.getComponent(i)).setBorder(new EmptyBorder(0, 0, 0, 0));
            }

            if (typeOfReservation.getComponent(i) instanceof AbstractButton) {
                ((AbstractButton) typeOfReservation.getComponent(i)).setBorderPainted(false);
            }
        }
        modeOfPayment = new javax.swing.JComboBox<>();
        for (int i = 0; i < typeOfReservation.getComponentCount(); i++) 
        {
            if (typeOfReservation.getComponent(i) instanceof JComponent) {
                ((JComponent) typeOfReservation.getComponent(i)).setBorder(new EmptyBorder(0, 0, 0, 0));
            }

            if (typeOfReservation.getComponent(i) instanceof AbstractButton) {
                ((AbstractButton) typeOfReservation.getComponent(i)).setBorderPainted(false);
            }
        }
        datePicker1 = new com.github.lgooddatepicker.components.DatePicker();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Add a reservation");

        mainPnl.setBackground(new java.awt.Color(255, 255, 255));
        mainPnl.setBorder(javax.swing.BorderFactory.createEmptyBorder(64, 64, 64, 64));

        jLabel1.setFont(puritanBold);
        jLabel1.setForeground(new java.awt.Color(35, 35, 35));
        jLabel1.setText("NEW RESERVATION");

        contactTxt.setBackground(new java.awt.Color(248, 248, 248));
        contactTxt.setFont(inter);
        contactTxt.setForeground(new java.awt.Color(129, 129, 129));
        contactTxt.setText("Contact number");
        contactTxt.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(218, 218, 218)), javax.swing.BorderFactory.createEmptyBorder(16, 16, 16, 16)));
        contactTxt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                contactTxtFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                contactTxtFocusLost(evt);
            }
        });

        nameTxt.setBackground(new java.awt.Color(248, 248, 248));
        nameTxt.setFont(inter);
        nameTxt.setForeground(new java.awt.Color(129, 129, 129));
        nameTxt.setText("Name");
        nameTxt.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(218, 218, 218)), javax.swing.BorderFactory.createEmptyBorder(16, 16, 16, 16)));
        nameTxt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                nameTxtFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                nameTxtFocusLost(evt);
            }
        });

        typeOfReservation.setBackground(new java.awt.Color(248, 248, 248));
        typeOfReservation.setFont(inter);
        typeOfReservation.setForeground(new java.awt.Color(35, 35, 35));
        typeOfReservation.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select service", "Alternator repair", "Battery repair" }));
        typeOfReservation.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(218, 218, 218)), javax.swing.BorderFactory.createEmptyBorder(16, 16, 16, 16)));

        modeOfPayment.setBackground(new java.awt.Color(248, 248, 248));
        modeOfPayment.setFont(inter);
        modeOfPayment.setForeground(new java.awt.Color(35, 35, 35));
        modeOfPayment.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        modeOfPayment.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(218, 218, 218)), javax.swing.BorderFactory.createEmptyBorder(16, 16, 16, 16)));

        datePicker1.setText("Date");
        datePicker1.setFont(inter);
        datePicker1.setForeground(new java.awt.Color(51, 51, 51));

        javax.swing.GroupLayout mainPnlLayout = new javax.swing.GroupLayout(mainPnl);
        mainPnl.setLayout(mainPnlLayout);
        mainPnlLayout.setHorizontalGroup(
            mainPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPnlLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(mainPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(contactTxt)
                    .addComponent(nameTxt, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(typeOfReservation, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(mainPnlLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(mainPnlLayout.createSequentialGroup()
                        .addComponent(datePicker1, javax.swing.GroupLayout.DEFAULT_SIZE, 239, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(modeOfPayment, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        mainPnlLayout.setVerticalGroup(
            mainPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPnlLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(nameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(contactTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(typeOfReservation, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(mainPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(modeOfPayment, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                    .addComponent(datePicker1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(78, Short.MAX_VALUE))
        );

        getContentPane().add(mainPnl, java.awt.BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void contactTxtFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_contactTxtFocusGained
        String contactValue = contactTxt.getText();

        if (contactValue.equals("Contact number")) {
            contactTxt.setText("");
            contactTxt.setForeground(new Color(35, 35, 35));
        }
    }//GEN-LAST:event_contactTxtFocusGained

    private void contactTxtFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_contactTxtFocusLost
        String contactValue = contactTxt.getText();

        if (contactValue.equals("")) {
            contactTxt.setText("Contact number");
            contactTxt.setForeground(new Color(129, 129, 129));
        }
    }//GEN-LAST:event_contactTxtFocusLost

    private void nameTxtFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nameTxtFocusGained
        String nameValue = nameTxt.getText();

        if (nameValue.equals("Name")) {
            nameTxt.setText("");
            nameTxt.setForeground(new Color(35, 35, 35));
        }
    }//GEN-LAST:event_nameTxtFocusGained

    private void nameTxtFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nameTxtFocusLost
        String nameValue = nameTxt.getText();

        if (nameValue.equals("")) {
            nameTxt.setText("Name");
            nameTxt.setForeground(new Color(129, 129, 129));
        }
    }//GEN-LAST:event_nameTxtFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            javax.swing.UIManager.setLookAndFeel("com.sun.java.swing.plaf.windows.WindowsLookAndFeel");
        } catch (Exception e) {
            System.out.println("UIManager Exception : " + e);
        }
        
        UIManager.put("ComboBox.borderPaintsFocus", Boolean.FALSE);
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewReservation().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField contactTxt;
    private com.github.lgooddatepicker.components.DatePicker datePicker1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel mainPnl;
    private javax.swing.JComboBox<String> modeOfPayment;
    private javax.swing.JTextField nameTxt;
    private javax.swing.JComboBox<String> typeOfReservation;
    // End of variables declaration//GEN-END:variables
}
