/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package screens;

import classes.Database;
import java.awt.Font;
import java.awt.Color;
import java.awt.Toolkit;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.Locale;
import javax.swing.JComponent;
import javax.swing.border.EmptyBorder;
import javax.swing.AbstractButton;
import javax.swing.UIManager;
import utils.FontLoader;

/**
 *
 * @author rwill
 */
public class ReservationDetails extends javax.swing.JFrame {
    FontLoader fontLoader = new FontLoader();
    Font inter;
    Font puritanBold;
    Main main;
    String name;
    String contactNumber;
    String date;
    String typeOfService;
    String modeOfPayment;
    String reservationId;
    String customerId;
    
    /**
     * Creates new form NewReservation
     */
    public ReservationDetails(Main main, String reservationId) {
        setFonts();
        initComponents();
        setFrameIcon();
        focus();
        
        this.main = main;
        this.reservationId = reservationId;
        
        fetchReservation();
        
    }

    public ReservationDetails() {
        setFonts();
        initComponents();
        setFrameIcon();
        focus();
    }
    
    private void fetchReservation() {
        try {
            String query = "SELECT * FROM laes.reservations WHERE reservationId = '" + this.reservationId + "'";
            PreparedStatement pstmt = Database.sqlConnection.prepareStatement(query);
            
            ResultSet rs = pstmt.executeQuery();
            
            while (rs.next()) {
                this.name = rs.getString("name");
                this.contactNumber = rs.getString("contactNumber");
                this.date = rs.getString("date");
                this.typeOfService = rs.getString("typeOfService");
                this.modeOfPayment = rs.getString("modeOfPayment");
                this.customerId = rs.getString("customerId");
                
                DateTimeFormatter formatter = DateTimeFormatter.ofPattern("yyyy-MM-dd");
                formatter = formatter.withLocale(Locale.ENGLISH);
                LocalDate date = LocalDate.parse(this.date, formatter);
                
                nameTxt.setText(this.name);
                contactTxt.setText(this.contactNumber);
                datePicker.setDate(date);
                typeOfServiceSelect.setSelectedItem(this.typeOfService);
                modeOfPaymentSelect.setSelectedItem(this.modeOfPayment);
                referenceTxt.setText("#" + this.reservationId);
            }
        } catch (SQLException e) {
            System.out.println(e);
        }
    }
    
    private void setFonts() {
        inter = fontLoader.interRegular(12);
        puritanBold = fontLoader.puritanBold(44);
    }
    
    private void setFrameIcon() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("../assets/logo.png")));
    }
    
    private void focus() {
        mainPnl.requestFocus();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPnl = new javax.swing.JPanel();
        referenceTxt = new javax.swing.JLabel();
        contactTxt = new javax.swing.JTextField();
        nameTxt = new javax.swing.JTextField();
        typeOfServiceSelect = new javax.swing.JComboBox<>();
        for (int i = 0; i < typeOfServiceSelect.getComponentCount(); i++) 
        {
            if (typeOfServiceSelect.getComponent(i) instanceof JComponent) {
                ((JComponent) typeOfServiceSelect.getComponent(i)).setBorder(new EmptyBorder(0, 0, 0, 0));
            }

            if (typeOfServiceSelect.getComponent(i) instanceof AbstractButton) {
                ((AbstractButton) typeOfServiceSelect.getComponent(i)).setBorderPainted(false);
            }
        }
        datePicker = new com.github.lgooddatepicker.components.DatePicker();
        saveBtn = new javax.swing.JButton();
        cancelBtn = new javax.swing.JButton();
        modeOfPaymentSelect = new javax.swing.JComboBox<>();
        for (int i = 0; i < modeOfPaymentSelect.getComponentCount(); i++) 
        {
            if (modeOfPaymentSelect.getComponent(i) instanceof JComponent) {
                ((JComponent) modeOfPaymentSelect.getComponent(i)).setBorder(new EmptyBorder(0, 0, 0, 0));
            }

            if (modeOfPaymentSelect.getComponent(i) instanceof AbstractButton) {
                ((AbstractButton) modeOfPaymentSelect.getComponent(i)).setBorderPainted(false);
            }
        }
        deleteBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Add a reservation");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        mainPnl.setBackground(new java.awt.Color(255, 255, 255));
        mainPnl.setBorder(javax.swing.BorderFactory.createEmptyBorder(64, 64, 64, 64));

        referenceTxt.setText("REFERENCE #");
        referenceTxt.setFont(puritanBold);
        referenceTxt.setForeground(new java.awt.Color(35, 35, 35));

        contactTxt.setFont(inter);
        contactTxt.setText("Contact number");
        contactTxt.setBackground(new java.awt.Color(248, 248, 248));
        contactTxt.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(218, 218, 218)), javax.swing.BorderFactory.createEmptyBorder(16, 16, 16, 16)));
        contactTxt.setForeground(new java.awt.Color(35, 35, 35));
        contactTxt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                contactTxtFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                contactTxtFocusLost(evt);
            }
        });

        nameTxt.setFont(inter);
        nameTxt.setText("Name");
        nameTxt.setBackground(new java.awt.Color(248, 248, 248));
        nameTxt.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(218, 218, 218)), javax.swing.BorderFactory.createEmptyBorder(16, 16, 16, 16)));
        nameTxt.setForeground(new java.awt.Color(35, 35, 35));
        nameTxt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                nameTxtFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                nameTxtFocusLost(evt);
            }
        });

        typeOfServiceSelect.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Type of service", "Alternator repair", "Battery repair" }));
        typeOfServiceSelect.setBackground(new java.awt.Color(248, 248, 248));
        typeOfServiceSelect.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(218, 218, 218)), javax.swing.BorderFactory.createEmptyBorder(16, 16, 16, 16)));
        typeOfServiceSelect.setFont(inter);
        typeOfServiceSelect.setForeground(new java.awt.Color(35, 35, 35));

        datePicker.setText("Date");
        datePicker.setFont(inter);
        datePicker.setForeground(new java.awt.Color(51, 51, 51));

        saveBtn.setText("Save");
        saveBtn.setBackground(new java.awt.Color(40, 40, 40));
        saveBtn.setBorder(javax.swing.BorderFactory.createEmptyBorder(16, 16, 16, 16));
        saveBtn.setBorderPainted(false);
        saveBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        saveBtn.setFocusPainted(false);
        saveBtn.setFont(inter);
        saveBtn.setForeground(new java.awt.Color(248, 248, 248));
        saveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveBtnActionPerformed(evt);
            }
        });

        cancelBtn.setText("Cancel");
        cancelBtn.setBackground(new java.awt.Color(245, 245, 245));
        cancelBtn.setBorder(javax.swing.BorderFactory.createEmptyBorder(16, 16, 16, 16));
        cancelBtn.setBorderPainted(false);
        cancelBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cancelBtn.setFocusPainted(false);
        cancelBtn.setFont(inter);
        cancelBtn.setForeground(new java.awt.Color(129, 129, 129));
        cancelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelBtnActionPerformed(evt);
            }
        });

        modeOfPaymentSelect.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mode of payment", "Cash", "GCash" }));
        modeOfPaymentSelect.setBackground(new java.awt.Color(248, 248, 248));
        modeOfPaymentSelect.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(218, 218, 218)), javax.swing.BorderFactory.createEmptyBorder(16, 16, 16, 16)));
        modeOfPaymentSelect.setFont(inter);
        modeOfPaymentSelect.setForeground(new java.awt.Color(35, 35, 35));

        deleteBtn.setText("Delete");
        deleteBtn.setBackground(new java.awt.Color(197, 59, 59));
        deleteBtn.setBorder(javax.swing.BorderFactory.createEmptyBorder(16, 16, 16, 16));
        deleteBtn.setBorderPainted(false);
        deleteBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        deleteBtn.setFocusPainted(false);
        deleteBtn.setFont(inter);
        deleteBtn.setForeground(new java.awt.Color(248, 248, 248));
        deleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout mainPnlLayout = new javax.swing.GroupLayout(mainPnl);
        mainPnl.setLayout(mainPnlLayout);
        mainPnlLayout.setHorizontalGroup(
            mainPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPnlLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(mainPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(contactTxt)
                    .addComponent(nameTxt, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(typeOfServiceSelect, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(saveBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cancelBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(mainPnlLayout.createSequentialGroup()
                        .addComponent(referenceTxt)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainPnlLayout.createSequentialGroup()
                        .addComponent(datePicker, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(modeOfPaymentSelect, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(deleteBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        mainPnlLayout.setVerticalGroup(
            mainPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPnlLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(referenceTxt)
                .addGap(18, 18, 18)
                .addComponent(nameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(contactTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(typeOfServiceSelect, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(mainPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(modeOfPaymentSelect, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(datePicker, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addComponent(saveBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(deleteBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cancelBtn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(mainPnl, java.awt.BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void contactTxtFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_contactTxtFocusGained
        String contactValue = contactTxt.getText();

        if (contactValue.equals("Contact number")) {
            contactTxt.setText("");
            contactTxt.setForeground(new Color(35, 35, 35));
        }
    }//GEN-LAST:event_contactTxtFocusGained

    private void contactTxtFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_contactTxtFocusLost
        String contactValue = contactTxt.getText();

        if (contactValue.equals("")) {
            contactTxt.setText("Contact number");
            contactTxt.setForeground(new Color(129, 129, 129));
        }
    }//GEN-LAST:event_contactTxtFocusLost

    private void nameTxtFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nameTxtFocusGained
        String nameValue = nameTxt.getText();

        if (nameValue.equals("Name")) {
            nameTxt.setText("");
            nameTxt.setForeground(new Color(35, 35, 35));
        }
    }//GEN-LAST:event_nameTxtFocusGained

    private void nameTxtFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nameTxtFocusLost
        String nameValue = nameTxt.getText();

        if (nameValue.equals("")) {
            nameTxt.setText("Name");
            nameTxt.setForeground(new Color(129, 129, 129));
        }
    }//GEN-LAST:event_nameTxtFocusLost

    private void saveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveBtnActionPerformed
        String name = nameTxt.getText();
        String contactNumber = contactTxt.getText();
        LocalDate date = datePicker.getDate();
        String service = typeOfServiceSelect.getSelectedItem().toString();
        String payment = modeOfPaymentSelect.getSelectedItem().toString();
        
        try {
            String query = "UPDATE laes.reservations SET " +
                "name = '" + name + "', " +
                "contactNumber = '" + contactNumber + "', " +
                "date = '" + date + "', " +
                "typeOfService = '" + service + "', " +
                "modeOfPayment = '" + payment + "' " +
                "WHERE reservationId = '" + this.reservationId + "'";
            PreparedStatement pstmt = Database.sqlConnection.prepareStatement(query);
            
            pstmt.executeUpdate();
            
            System.out.println("Successfully updated reservation " + this.reservationId + " data");
                
            try {
                String customerQuery = "UPDATE laes.customers SET " +
                    "name = '" + name + "', " +
                    "contactNumber = '" + contactNumber + "' " +
                    "WHERE customerId = '" + this.customerId + "'";
                PreparedStatement customerPstmt = Database.sqlConnection.prepareStatement(customerQuery);

                customerPstmt.executeUpdate();

                System.out.println("Updated customerId " + this.customerId + " as well");

                this.main.fetchReservations();
                this.main.fetchCustomers();
                this.dispose();
            } catch (SQLException err) {
                System.out.println(err);
            }
            
            this.main.fetchReservations();
            this.dispose();
        } catch (SQLException err) {
            System.out.println(err);
        }
    }//GEN-LAST:event_saveBtnActionPerformed

    private void cancelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelBtnActionPerformed
        this.dispose();
    }//GEN-LAST:event_cancelBtnActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // fetch data again from database
    }//GEN-LAST:event_formWindowClosed

    private void deleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBtnActionPerformed
        try {
            String query = "DELETE FROM laes.reservations WHERE reservationId = '" + this.reservationId + "'";
            PreparedStatement pstmt = Database.sqlConnection.prepareStatement(query);
            
            pstmt.executeUpdate();
            
            System.out.println("Successfully deleted reservation " + this.reservationId + " data");
            
            try {
                String servicesQuery = "SELECT * from laes.customers WHERE customerId = '" + customerId + "'";
                PreparedStatement servicesPstmt = Database.sqlConnection.prepareStatement(servicesQuery);
                ResultSet servicesRs = servicesPstmt.executeQuery();
                    
                if (servicesRs.next()) {
                    int currentServices = 0;
                    
                    currentServices = servicesRs.getInt("services");
                        
                    if (currentServices > 1) {
                        String customerQuery = "UPDATE laes.customers SET services = " + (currentServices - 1) + " WHERE customerId = '" + customerId + "'";
                        PreparedStatement customerPstmt = Database.sqlConnection.prepareStatement(customerQuery);

                        customerPstmt.executeUpdate();

                        System.out.println("Removed service from customerId " + customerId);
                    } else {
                        String customerQuery = "DELETE FROM laes.customers WHERE customerId = '" + customerId + "'";
                        PreparedStatement customerPstmt = Database.sqlConnection.prepareStatement(customerQuery);

                        customerPstmt.executeUpdate();

                        System.out.println("Deleted customer with customerId " + customerId);
                    }
                    
                    this.main.fetchCustomers();
                }
            } catch (SQLException e) {
                System.out.println(e);
            }
            
            this.main.fetchReservations();
            this.dispose();
        } catch (SQLException err) {
            System.out.println(err);
        }
    }//GEN-LAST:event_deleteBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            javax.swing.UIManager.setLookAndFeel("com.sun.java.swing.plaf.windows.WindowsLookAndFeel");
        } catch (Exception e) {
            System.out.println("UIManager Exception : " + e);
        }
        
        UIManager.put("ComboBox.borderPaintsFocus", Boolean.FALSE);
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ReservationDetails().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelBtn;
    private javax.swing.JTextField contactTxt;
    private com.github.lgooddatepicker.components.DatePicker datePicker;
    private javax.swing.JButton deleteBtn;
    private javax.swing.JPanel mainPnl;
    private javax.swing.JComboBox<String> modeOfPaymentSelect;
    private javax.swing.JTextField nameTxt;
    private javax.swing.JLabel referenceTxt;
    private javax.swing.JButton saveBtn;
    private javax.swing.JComboBox<String> typeOfServiceSelect;
    // End of variables declaration//GEN-END:variables
}
