/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package classes;

import java.io.IOException;
import java.sql.Blob;
import java.sql.SQLException;
import javax.swing.ImageIcon;
import javax.swing.SwingWorker;
import screens.ItemDetails;
import screens.Main;

/**
 *
 * @author john michael
 */
public class ProductPanel extends javax.swing.JPanel {
    private Main main;
    
    private final int databaseId;
    private String productName;
    private int quantity;
    private Blob pictureBlob;
    
    /**
     * Creates new form Product
     * @param main
     * @param databaseId
     * @param productName
     * @param quantity
     * @param pictureBlob
     */
    public ProductPanel(
        Main main,
        int databaseId,
        String productName,
        int quantity,
        Blob pictureBlob
    ) {
        this.main = main;
        this.databaseId = databaseId;
        this.productName = productName;
        this.quantity = quantity;
        this.pictureBlob = pictureBlob;

        initComponents();
        initRender();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        topPadding = new javax.swing.JPanel();
        imageRow = new javax.swing.JPanel();
        imageContainer = new javax.swing.JPanel();
        productImageLabel = new javax.swing.JLabel();
        bottomPadding = new javax.swing.JPanel();
        bottomRow = new javax.swing.JPanel();
        buttonRow = new javax.swing.JPanel();
        decrementButton = new javax.swing.JButton();
        productNameLabel = new java.awt.Label();
        incrementButton = new javax.swing.JButton();
        countRow = new javax.swing.JPanel();
        countLabel = new java.awt.Label();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.Y_AXIS));

        topPadding.setBackground(new java.awt.Color(255, 255, 255));
        topPadding.setPreferredSize(new java.awt.Dimension(183, 12));

        javax.swing.GroupLayout topPaddingLayout = new javax.swing.GroupLayout(topPadding);
        topPadding.setLayout(topPaddingLayout);
        topPaddingLayout.setHorizontalGroup(
            topPaddingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 183, Short.MAX_VALUE)
        );
        topPaddingLayout.setVerticalGroup(
            topPaddingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 14, Short.MAX_VALUE)
        );

        add(topPadding);

        imageRow.setBackground(new java.awt.Color(255, 255, 255));
        imageRow.setPreferredSize(new java.awt.Dimension(183, 128));

        imageContainer.setBackground(new java.awt.Color(225, 225, 225));
        imageContainer.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        productImageLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        productImageLabel.setText("image");
        productImageLabel.setToolTipText("");
        productImageLabel.setAlignmentX(0.5F);
        productImageLabel.setPreferredSize(new java.awt.Dimension(130, 130));
        productImageLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                productImageLabelMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout imageContainerLayout = new javax.swing.GroupLayout(imageContainer);
        imageContainer.setLayout(imageContainerLayout);
        imageContainerLayout.setHorizontalGroup(
            imageContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 130, Short.MAX_VALUE)
            .addGroup(imageContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(imageContainerLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(productImageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        imageContainerLayout.setVerticalGroup(
            imageContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 130, Short.MAX_VALUE)
            .addGroup(imageContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(imageContainerLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(productImageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        imageRow.add(imageContainer);

        add(imageRow);

        bottomPadding.setBackground(new java.awt.Color(255, 255, 255));
        bottomPadding.setPreferredSize(new java.awt.Dimension(183, 12));

        javax.swing.GroupLayout bottomPaddingLayout = new javax.swing.GroupLayout(bottomPadding);
        bottomPadding.setLayout(bottomPaddingLayout);
        bottomPaddingLayout.setHorizontalGroup(
            bottomPaddingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 183, Short.MAX_VALUE)
        );
        bottomPaddingLayout.setVerticalGroup(
            bottomPaddingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 14, Short.MAX_VALUE)
        );

        add(bottomPadding);

        bottomRow.setBackground(new java.awt.Color(255, 255, 255));
        bottomRow.setPreferredSize(new java.awt.Dimension(183, 64));
        bottomRow.setLayout(new javax.swing.BoxLayout(bottomRow, javax.swing.BoxLayout.Y_AXIS));

        buttonRow.setBackground(new java.awt.Color(255, 255, 255));

        decrementButton.setBackground(new java.awt.Color(192, 192, 192));
        decrementButton.setForeground(new java.awt.Color(64, 64, 64));
        decrementButton.setText("-");
        decrementButton.setOpaque(true);
        decrementButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                decrementButtonActionPerformed(evt);
            }
        });
        buttonRow.add(decrementButton);

        productNameLabel.setAlignment(java.awt.Label.CENTER);
        productNameLabel.setMaximumSize(new java.awt.Dimension(72, 20));
        productNameLabel.setMinimumSize(new java.awt.Dimension(72, 20));
        productNameLabel.setName(""); // NOI18N
        productNameLabel.setText(productName);
        buttonRow.add(productNameLabel);

        incrementButton.setBackground(new java.awt.Color(192, 192, 192));
        incrementButton.setForeground(new java.awt.Color(64, 64, 64));
        incrementButton.setText("+");
        incrementButton.setAlignmentY(0.0F);
        incrementButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                incrementButtonActionPerformed(evt);
            }
        });
        buttonRow.add(incrementButton);

        bottomRow.add(buttonRow);

        countRow.setBackground(new java.awt.Color(255, 255, 255));

        countLabel.setText("" + quantity + " pcs");
        countRow.add(countLabel);

        bottomRow.add(countRow);

        add(bottomRow);
    }// </editor-fold>//GEN-END:initComponents

    public Main getMain() {
        return main;
    }
    
    public int getDatabaseId() {
        return databaseId;
    }
    
    public String getProductName() {
        return productName;
    }
    
    public void setProductName(String productName) {
        this.productName = productName;
        
        renderProductName();
    }
    
    public int getQuantity() {
        return quantity;
    }
    
    public void setQuantity(int quantity) {
        this.quantity = quantity;
        
        renderQuantity();
    }
    
    public Blob getPictureBlob() {
        return pictureBlob;
    }
    
    public void setPictureBlob(Blob blob) {
        this.pictureBlob = blob;
        
        renderPictureBlob();
    }
    
    private void decrementButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_decrementButtonActionPerformed
        // TODO add your handling code here:

        if (quantity <= 0) {
            return;
        }
        
        quantity -= 1;
        renderQuantity();
        this.updateDatabase();
    }//GEN-LAST:event_decrementButtonActionPerformed

    private void incrementButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_incrementButtonActionPerformed
        // TODO add your handling code here:
        
        quantity += 1;
        
        countLabel.setText("" + quantity + " pcs");
        renderQuantity();
        this.updateDatabase();
    }//GEN-LAST:event_incrementButtonActionPerformed

    private void productImageLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_productImageLabelMouseClicked
        // TODO add your handling code here:
        
        System.out.println("You clicked on the product: '" + productName + "'.");
        
        var panel = new ItemDetails(this);
        
        panel.setVisible(true);
    }//GEN-LAST:event_productImageLabelMouseClicked
    
    private void updateDatabase() {
        try {
            var string = "UPDATE laes.products "
                       + "SET name = ?, quantity = ?, picture = ? "
                       + "WHERE id = ?";
            var stmt = Database.sqlConnection.prepareStatement(string);
            stmt.setString(1, this.productName);
            stmt.setInt(2, this.quantity);
            stmt.setBlob(3, this.pictureBlob);
            stmt.setInt(4, this.databaseId);
            
            stmt.executeUpdate();
        } catch (SQLException exception) {
            System.out.println("The SQL went wrong in [updateDatabase]! Error: " + exception.getMessage());
        }
    }
    
    private void initRender() {
        if (pictureBlob != null) {
            renderPictureBlob();
        }
        System.out.println(pictureBlob);
    }
    
    private void renderProductName() {
        productNameLabel.setText(productName);
        
        this.repaint();
        this.revalidate();
    }
    
    private void renderQuantity() {
        countLabel.setText("" + quantity + " pcs");
    
        this.repaint();
        this.revalidate();
    }
    
    private void renderPictureBlob() {
        var worker = new SwingWorker() {
            @Override
            protected Object doInBackground()  {
                try {
                    var blob = pictureBlob;
                    var stream = blob.getBinaryStream().readAllBytes();
            
                    var imageIcon = new ImageIcon(stream);
                    productImageLabel.setIcon(imageIcon);
                    revalidate();
                } catch (IOException exception) {
                    System.out.println("Failed reading the image. Error: " + exception.getMessage());
                } catch (SQLException exception) {
                    System.out.println("SQL Failed! Error: " + exception.getMessage());
                }
                
                return null;
            }
        };
        worker.execute();
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bottomPadding;
    private javax.swing.JPanel bottomRow;
    private javax.swing.JPanel buttonRow;
    private java.awt.Label countLabel;
    private javax.swing.JPanel countRow;
    private javax.swing.JButton decrementButton;
    private javax.swing.JPanel imageContainer;
    private javax.swing.JPanel imageRow;
    private javax.swing.JButton incrementButton;
    private javax.swing.JLabel productImageLabel;
    private java.awt.Label productNameLabel;
    private javax.swing.JPanel topPadding;
    // End of variables declaration//GEN-END:variables
}
